CREATE TABLE gift_idea (
    gift_name TEXT,
    gender TEXT,
    age TEXT,
    occasion TEXT,
    interest TEXT
);

INSERT INTO gift_idea (gift_name, gender, age, occasion, interest) VALUES
('Glow-in-the-Dark Soccer Ball', 'male', 'child', 'birthday', 'sports'),
('Custom Pet Puzzle', 'female', 'adult', 'holidays', 'pets'),
('Bluetooth Karaoke Microphone', 'female', 'teen', 'birthday', 'music'),
('Sketch Pad & Marker Set', 'female', 'teen', 'holidays', 'art'),
('Mini Baking Kit', 'female', 'child', 'birthday', 'cooking'),
('Building Blocks Starter Set', 'male', 'child', 'birthday', 'toys'),
('Gaming Mouse with RGB', 'male', 'teen', 'holidays', 'video games'),
('Personalized Dog Leash', 'female', 'adult', 'wedding', 'pets'),
('Basketball Training Hoop', 'male', 'teen', 'birthday', 'sports'),
('Vinyl Record Subscription', 'male', 'young-adult', 'holidays', 'music'),
('Watercolor Travel Set', 'female', 'young-adult', 'graduation', 'art'),
('Gourmet Spice Kit', 'male', 'adult', 'birthday', 'cooking'),
('Remote-Control Toy Car', 'male', 'child', 'birthday', 'toys'),
('Console Game Store Gift Card', 'male', 'teen', 'birthday', 'video games'),
('Pet Camera with Treat Dispenser', 'female', 'adult', 'holidays', 'pets'),
('Yoga Ball & Mat Set', 'female', 'young-adult', 'birthday', 'sports'),
('Lo-Fi Music Creator Kit', 'male', 'young-adult', 'birthday', 'music'),
('Acrylic Paint Kit', 'female', 'teen', 'birthday', 'art'),
('Pizza Making Starter Set', 'male', 'adult', 'holidays', 'cooking'),
('Stuffed Dinosaur Plush Toy', 'female', 'child', 'birthday', 'toys'),
('RGB Gaming Keyboard', 'male', 'teen', 'graduation', 'video games'),
('Pet Memorial Frame', 'female', 'adult', 'wedding', 'pets'),
('Tennis Racket & Ball Combo', 'male', 'teen', 'birthday', 'sports'),
('Music Note Jewelry Box', 'female', 'young-adult', 'birthday', 'music'),
('Wood Burn Art Kit', 'male', 'adult', 'birthday', 'art'),
('Herbal Tea Brewing Kit', 'female', 'adult', 'holidays', 'cooking'),
('Plush Toy Building Kit', 'female', 'child', 'birthday', 'toys'),
('Digital Game Pass Subscription', 'male', 'young-adult', 'holidays', 'video games'),
('Pet-Themed Board Game', 'female', 'teen', 'birthday', 'pets'),
('Soccer Skills Ladder Set', 'male', 'teen', 'holidays', 'sports'),
('Mini Synthesizer', 'male', 'young-adult', 'graduation', 'music'),
('Stained Glass Craft Kit', 'female', 'adult', 'birthday', 'art'),
('DIY Pasta Making Kit', 'female', 'adult', 'wedding', 'cooking'),
('Talking Toy Robot', 'male', 'child', 'birthday', 'toys'),
('Gaming Wall Art Poster Set', 'male', 'teen', 'birthday', 'video games'),
('Pet Grooming Glove', 'female', 'adult', 'holidays', 'pets'),
('Adjustable Dumbbells', 'male', 'adult', 'birthday', 'sports'),
('Record Your Own Song Kit', 'female', 'teen', 'graduation', 'music'),
('Mosaic Tile Art Box', 'female', 'young-adult', 'birthday', 'art'),
('Sushi Rolling Starter Kit', 'male', 'adult', 'birthday', 'cooking'),
('Foam Archery Set', 'male', 'child', 'birthday', 'toys'),
('Gaming Chair Footrest Combo', 'male', 'teen', 'holidays', 'video games'),
('Custom Pet Portrait Canvas', 'female', 'adult', 'wedding', 'pets'),
('Portable Ping Pong Set', 'male', 'teen', 'holidays', 'sports'),
('Vintage Cassette Player', 'male', 'young-adult', 'birthday', 'music'),
('DIY Embroidery Kit', 'female', 'young-adult', 'holidays', 'art'),
('Slow Cooker Cookbook', 'female', 'adult', 'holidays', 'cooking'),
('Educational Puzzle Toy', 'female', 'child', 'birthday', 'toys'),
('Game Streaming Light Kit', 'male', 'young-adult', 'graduation', 'video games'),
('Pet Travel Backpack', 'female', 'young-adult', 'holidays', 'pets'),
('Smart Soccer Ball with App', 'male', 'teen', 'birthday', 'sports'),
('Build-Your-Own Synth Kit', 'male', 'young-adult', 'graduation', 'music'),
('Glow Sand Art Board', 'female', 'child', 'birthday', 'art'),
('Gourmet Herb Garden Kit', 'female', 'adult', 'wedding', 'cooking'),
('Magnetic Tile Building Set', 'male', 'child', 'birthday', 'toys'),
('Retro Handheld Game Console', 'male', 'teen', 'holidays', 'video games'),
('Custom Pet Name Mug', 'female', 'adult', 'holidays', 'pets'),
('Balance Board Trainer', 'male', 'teen', 'birthday', 'sports'),
('Vinyl Wall Clock (Music Theme)', 'female', 'young-adult', 'birthday', 'music'),
('DIY Resin Jewelry Kit', 'female', 'teen', 'birthday', 'art'),
('Molecular Cooking Science Set', 'male', 'adult', 'holidays', 'cooking'),
('Toy Vending Machine Playset', 'male', 'child', 'birthday', 'toys'),
('Esports Team Jersey', 'male', 'teen', 'graduation', 'video games'),
('Pet Treat Baking Kit', 'female', 'adult', 'birthday', 'pets'),
('Speed Agility Ladder Kit', 'male', 'teen', 'holidays', 'sports'),
('Songwriting Notebook + Guide', 'female', 'young-adult', 'birthday', 'music'),
('Glass Etching Starter Pack', 'female', 'adult', 'holidays', 'art'),
('Electric Crepe Maker', 'female', 'adult', 'birthday', 'cooking'),
('Foam Building Bricks', 'male', 'child', 'birthday', 'toys'),
('Gaming Desk Organizer', 'male', 'teen', 'birthday', 'video games'),
('Cat-Themed Blanket', 'female', 'adult', 'holidays', 'pets'),
('Basketball Strategy Board', 'male', 'teen', 'birthday', 'sports'),
('Mini Turntable Music Kit', 'female', 'young-adult', 'birthday', 'music'),
('Clay Modeling Set', 'female', 'child', 'birthday', 'art'),
('Digital Meat Thermometer', 'male', 'adult', 'wedding', 'cooking'),
('STEM Toy Circuit Board', 'female', 'child', 'holidays', 'toys'),
('Game Soundtrack Vinyl Collection', 'male', 'young-adult', 'birthday', 'video games'),
('Pet Puzzle Feeder', 'male', 'adult', 'holidays', 'pets'),
('Indoor Mini Basketball Hoop', 'male', 'teen', 'birthday', 'sports'),
('Bluetooth Music Beanie', 'female', 'teen', 'holidays', 'music'),
('Color-Changing Paint Markers', 'female', 'teen', 'birthday', 'art'),
('Artisan Bread Baking Set', 'female', 'adult', 'holidays', 'cooking'),
('Magnetic Maze Puzzle Box', 'male', 'child', 'birthday', 'toys'),
('Custom Gamer Tag Sign', 'male', 'teen', 'birthday', 'video games'),
('Pet Face Pillow', 'female', 'adult', 'birthday', 'pets'),
('Smart Jump Rope', 'female', 'teen', 'holidays', 'sports'),
('Bluetooth Sheet Music Display', 'female', 'young-adult', 'graduation', 'music'),
('DIY Paint-by-Number Portrait', 'female', 'adult', 'birthday', 'art'),
('Waffle Iron with Mix Kit', 'female', 'adult', 'wedding', 'cooking'),
('Talking Animal Toy', 'male', 'child', 'birthday', 'toys'),
('Retro Pixel Art Game Lamp', 'male', 'teen', 'birthday', 'video games'),
('Pet Camera with Night Vision', 'female', 'adult', 'wedding', 'pets'),
('Foam Archery Bow Set', 'male', 'child', 'holidays', 'sports'),
('Custom Song Wall Print', 'female', 'young-adult', 'birthday', 'music'),
('Alcohol Ink Painting Kit', 'female', 'adult', 'holidays', 'art'),
('Culinary Torch Gift Set', 'male', 'adult', 'birthday', 'cooking'),
('Mini Lab Science Toy', 'male', 'child', 'birthday', 'toys'),
('Gaming Strategy Card Deck', 'male', 'teen', 'birthday', 'video games'),
('Interactive Puppy Plush Toy', 'female', 'child', 'birthday', 'pets'),
('Portable Basketball Hoop', 'male', 'teen', 'birthday', 'sports'),
('Digital Sheet Music Display', 'female', 'young-adult', 'graduation', 'music'),
('Oil Pastel Art Kit', 'female', 'teen', 'holidays', 'art'),
('Beginner Baking Set', 'female', 'child', 'birthday', 'cooking'),
('Magnetic Building Blocks', 'male', 'child', 'birthday', 'toys'),
('Console Game Gift Card', 'male', 'teen', 'birthday', 'video games'),
('Cat Scratcher Lounge', 'female', 'adult', 'wedding', 'pets'),
('Soccer Agility Training Set', 'male', 'teen', 'holidays', 'sports'),
('Custom Vinyl Music Clock', 'male', 'young-adult', 'birthday', 'music'),
('Stained Glass Craft Kit', 'female', 'adult', 'holidays', 'art'),
('Pizza Stone Cooking Kit', 'male', 'adult', 'birthday', 'cooking'),
('Stuffed Animal Building Kit', 'female', 'child', 'birthday', 'toys'),
('Gaming Controller Holder', 'male', 'teen', 'holidays', 'video games'),
('Pet Hair Grooming Vacuum', 'female', 'adult', 'holidays', 'pets'),
('Glow-in-the-Dark Sports Cones', 'male', 'child', 'birthday', 'sports'),
('Bluetooth Turntable', 'female', 'young-adult', 'birthday', 'music'),
('Sculpture Clay Starter Pack', 'female', 'adult', 'birthday', 'art'),
('Sous Vide Starter Kit', 'male', 'adult', 'wedding', 'cooking'),
('RC Dinosaur Toy', 'male', 'child', 'birthday', 'toys'),
('Wireless Gaming Headset', 'male', 'teen', 'graduation', 'video games'),
('Pet DNA Test Kit', 'female', 'adult', 'birthday', 'pets'),
('Foam Finger Rocket Set', 'male', 'child', 'holidays', 'sports'),
('Mini Guitar for Beginners', 'female', 'teen', 'birthday', 'music'),
('DIY Mosaic Tile Coasters', 'female', 'adult', 'birthday', 'art'),
('Gourmet Cupcake Kit', 'female', 'young-adult', 'holidays', 'cooking'),
('Stacking Animal Toys', 'male', 'child', 'birthday', 'toys'),
('Video Game History Poster', 'male', 'teen', 'birthday', 'video games'),
('Pet ID Tag Engraving Kit', 'female', 'adult', 'wedding', 'pets'),
('Tennis Racket Grip Pack', 'male', 'teen', 'birthday', 'sports'),
('Vintage Microphone Replica', 'male', 'young-adult', 'birthday', 'music'),
('Brush Pen Calligraphy Kit', 'female', 'teen', 'holidays', 'art'),
('French Cooking Class Voucher', 'female', 'adult', 'wedding', 'cooking'),
('Interactive Learning Robot', 'male', 'child', 'birthday', 'toys'),
('LED Gamer Desk Lamp', 'male', 'teen', 'birthday', 'video games'),
('Pet Backpack Carrier', 'female', 'young-adult', 'holidays', 'pets'),
('Basketball Strategy Playbook', 'male', 'teen', 'birthday', 'sports'),
('Music Theory Puzzle Game', 'female', 'young-adult', 'graduation', 'music'),
('DIY Art Resin Tray Kit', 'female', 'adult', 'birthday', 'art'),
('Sushi Making Kit', 'male', 'adult', 'birthday', 'cooking'),
('Color Match Puzzle Toy', 'female', 'child', 'birthday', 'toys'),
('Console Skin Customizer', 'male', 'teen', 'holidays', 'video games'),
('Personalized Pet Calendar', 'female', 'adult', 'holidays', 'pets'),
('Soccer Goal Set', 'male', 'child', 'birthday', 'sports'),
('Lo-Fi Chill Beats Kit', 'male', 'young-adult', 'birthday', 'music'),
('Glow Paint Starter Kit', 'female', 'teen', 'birthday', 'art'),
('Mini Ice Cream Machine', 'female', 'adult', 'holidays', 'cooking'),
('Robot Arm Building Kit', 'male', 'teen', 'birthday', 'toys'),
('Game Developer Starter Guide', 'male', 'young-adult', 'graduation', 'video games'),
('Custom Pet Collar with Name Tag', 'female', 'adult', 'birthday', 'pets'),
('Mini Basketball Arcade Game', 'male', 'teen', 'holidays', 'sports'),
('Vinyl Record Cleaning Kit', 'male', 'young-adult', 'graduation', 'music'),
('Mandala Coloring Book Set', 'female', 'teen', 'birthday', 'art'),
('DIY Sushi Rolling Mat Set', 'male', 'adult', 'holidays', 'cooking'),
('Interactive Alphabet Toy Mat', 'female', 'child', 'birthday', 'toys'),
('Gaming Console Carry Case', 'male', 'teen', 'birthday', 'video games'),
('Pet-Themed Wall Decals', 'female', 'adult', 'holidays', 'pets'),
('Speed & Agility Ladder Set', 'male', 'teen', 'birthday', 'sports'),
('Portable Bluetooth Speaker', 'female', 'young-adult', 'birthday', 'music'),
('Glass Painting Starter Kit', 'female', 'adult', 'birthday', 'art'),
('Pasta Making Roller Machine', 'male', 'adult', 'wedding', 'cooking'),
('Stuffed Animal Backpack', 'female', 'child', 'birthday', 'toys'),
('Retro Arcade Button Controller', 'male', 'teen', 'birthday', 'video games'),
('Custom Dog Bandana Set', 'female', 'adult', 'holidays', 'pets'),
('Football Toss Target Set', 'male', 'teen', 'holidays', 'sports'),
('Mini Keyboard Synthesizer', 'female', 'young-adult', 'graduation', 'music'),
('3D Pen for Drawing Models', 'female', 'teen', 'birthday', 'art'),
('Indoor S’mores Maker', 'male', 'adult', 'holidays', 'cooking'),
('Animal Puzzle Floor Mat', 'female', 'child', 'birthday', 'toys'),
('Gaming Desk Mat with LED Edges', 'male', 'teen', 'holidays', 'video games'),
('Pet Paw Print Keepsake Kit', 'female', 'adult', 'wedding', 'pets'),
('Adjustable Soccer Net', 'male', 'child', 'birthday', 'sports'),
('Music Composition Journal', 'female', 'young-adult', 'birthday', 'music'),
('Origami Folding Kit', 'female', 'teen', 'holidays', 'art'),
('Chocolate Dipping Set', 'female', 'adult', 'birthday', 'cooking'),
('Pop-Up Toy Barn Playset', 'male', 'child', 'birthday', 'toys'),
('Gaming-Themed Wall Clock', 'male', 'teen', 'birthday', 'video games'),
('Pet Toy Organizer Basket', 'female', 'adult', 'holidays', 'pets'),
('Basketball Ball Return Net', 'male', 'teen', 'birthday', 'sports'),
('Electric Ukulele Starter Pack', 'female', 'young-adult', 'birthday', 'music'),
('Mosaic Mirror Craft Kit', 'female', 'teen', 'birthday', 'art'),
('Mini Donut Maker Machine', 'male', 'adult', 'holidays', 'cooking'),
('Magnetic Alphabet Toy Set', 'female', 'child', 'birthday', 'toys'),
('Gaming Glasses Anti-Glare', 'male', 'teen', 'graduation', 'video games'),
('Custom Pet Embroidered Pillow', 'female', 'adult', 'wedding', 'pets'),
('Soccer Ball Bag & Pump', 'male', 'teen', 'birthday', 'sports'),
('Vinyl Album Frame Display Set', 'male', 'young-adult', 'birthday', 'music'),
('Marble Art Swirl Kit', 'female', 'teen', 'birthday', 'art'),
('Gourmet Cookie Decorating Kit', 'female', 'adult', 'birthday', 'cooking'),
('Stackable Animal Blocks', 'female', 'child', 'birthday', 'toys'),
('Gaming Controller Skin Pack', 'male', 'teen', 'birthday', 'video games'),
('Pet Bath Towel Hoodie', 'female', 'adult', 'holidays', 'pets'),
('Portable Soccer Goal Set', 'male', 'child', 'birthday', 'sports'),
('Vintage Cassette Player', 'female', 'young-adult', 'birthday', 'music'),
('Foam Paint Blaster Kit', 'female', 'teen', 'birthday', 'art'),
('Indoor Herb Growing Kit', 'male', 'adult', 'wedding', 'cooking'),
('Shape Sorting Puzzle Cube', 'female', 'child', 'birthday', 'toys'),
('Game-Themed Notebook & Stickers', 'male', 'teen', 'birthday', 'video games');